from .analisi_esplorativa import grafico_barre_qualitative_risposta
from .analisi_esplorativa import grafico_dispersione_quantitative_risposta
from .arrays import grafico_due_vettori
from .datasets import grafico_progressione_diabete_vs_bmi
